services:
  web:
    build: .
    ports:
      - "8085:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - bankingnet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: internetbanking
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - bankingnet

volumes:
  dbdata:

networks:
  bankingnet:
